config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  get "restaurants/new", to: 'restaurants#new', as: 'new_restaurant' # Show create FORM
  post "restaurants", to: 'restaurants#create' # Create a new restaurant


  get "restaurants", to: 'restaurants#index' # Show all restaurants
  get "restaurants/:id", to: 'restaurants#show', as: 'restaurant' # Show one restaurant

  get 'restaurants/:id/edit', to: 'restaurants#edit', as: 'edit_restaurant' # Show edit FORM
  patch 'restaurants/:id', to: 'restaurants#update'

  delete 'restaurants/:id', to: 'restaurants#destroy', as: 'destroy_restaurant' # Remove one restaurant





  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save!
    redirect_to restaurant_path(restaurant)
  end

  def edit
  end

  def update
    @restaurant.update!(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
  <li>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
  - <%= restaurant.address %> -
  <%= link_to 'remove', destroy_restaurant_path(restaurant), data: { turbo_method: 'delete'} %>
  </li>
<% end %>

</ul>

<p>
  <%= link_to 'Add new Restaurant', new_restaurant_path %>
</p>

app/views/restaurants/new.html.erb
<h1>Add New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1>Restaurant</h1>

<p>Name: <%= @restaurant.name %></p>
<p>Address: <%= @restaurant.address %></p>
<p>Rating: <%= @restaurant.rating %></p>

<p>
  <%= link_to 'Edit This Restaurant', edit_restaurant_path(@restaurant) %>
</p>
<p>
  <%= link_to "View All Restaurants", restaurants_path %>
</p>